export type Row=Record<string,any>;
export const sectors=['Électricité','Industrie','Restauration','Commerce','Bâtiment','Services à la personne','Administration & collectivités','Transport & logistique','Automobile','Hôtellerie & tourisme','Numérique','Autres activités','À renseigner'];
export const statuses=['À contacter','En attente','Accepté','Refusé','À relancer'];
export const norm=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
export const dateLabel=(v:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('fr-FR'):'—';
export const name=(c?:Row)=>c?.denomination||c?.raisonSociale||'Entreprise';
export {request as api} from './supabase';
import {request as api} from './supabase';
const loading=new Map<string,Promise<void>>();
export function load(src:string,key:string){if((window as any)[key])return Promise.resolve();if(key==='cluster'&&(window as any).L?.markerClusterGroup)return Promise.resolve();if(loading.has(src))return loading.get(src)!;const p=new Promise<void>((resolve,reject)=>{const tag=document.createElement('script');tag.src=src;tag.onload=()=>resolve();tag.onerror=()=>{loading.delete(src);reject(Error('Cette fonction nécessite une connexion Internet.'));};document.body.appendChild(tag);});loading.set(src,p);return p;}
const xlsx=()=>load('https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js','XLSX');
export function download(data:any,filename:string,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export const headers=['Raison sociale','Dénomination commerciale','Siège social','Activité','Métiers','Secteurs','Adresse','Code postal','Ville','Pays','Téléphone','Portable','E-mail','Site web','SIRET','APE','Contact responsable','Fonction','Téléphone responsable','E-mail responsable','Accueil des stagiaires','Capacité','Latitude','Longitude','Précision localisation'];
export const toRow=(c:Row)=>[c.raisonSociale,c.denomination,c.siege,c.activite,c.metiers?.join(', '),c.secteurs?.join(', '),c.adresse,c.codePostal,c.ville,c.pays,c.telephone,c.portable,c.email,c.siteWeb,c.siret,c.ape,c.contactNom,c.contactFonction,c.contactTelephone,c.contactEmail,c.acceptation,c.capacite,c.lat,c.lon,c.geoPrecision].map(v=>v??'');
export async function exportList(list:Row[],format:string){if(!list.length)throw Error('Aucune entreprise à exporter.');const rows=[headers,...list.map(toRow)];if(format==='xlsx'){await xlsx();const X=(window as any).XLSX,wb=X.utils.book_new(),ws=X.utils.aoa_to_sheet(rows);ws['!cols']=headers.map((_,i)=>({wch:[0,1,6].includes(i)?32:22}));X.utils.book_append_sheet(wb,ws,'Entreprises');X.writeFile(wb,'entreprises-'+today()+'.xlsx');}else{const text='\uFEFF'+rows.map(row=>row.map(v=>{const s=String(v??'');return '"'+(/^[=+\-@]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"';}).join(';')).join('\r\n');download(text,'entreprises-'+today()+'.csv','text/csv;charset=utf-8');}}
export async function exportReports(reports:Row[],students:Row[],companies:Row[]){await xlsx();const X=(window as any).XLSX,wb=X.utils.book_new(),rows=[['Élève','Classe','Entreprise','Statut','Date du contact','Moyen','Interlocuteur','Compte rendu','Début PFMP','Fin PFMP'],...reports.map(r=>{const s=students.find(s=>s.id===r.student_id);return [s?.name,s?.class_name,name(companies.find(c=>c.id===r.company_id)),r.status,r.date,r.method,r.contact,r.notes,r.start_date,r.end_date];})];X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet(rows),'Démarches');X.writeFile(wb,'comptes-rendus-pfmp-'+today()+'.xlsx');}
export async function readWorkbook(file:File,identifiers=false){await xlsx();const X=(window as any).XLSX,wb=X.read(await file.arrayBuffer(),{type:'array',codepage:65001}),sheet=wb.Sheets[wb.SheetNames[0]],rows=X.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false}) as any[][];if(identifiers){const raw=X.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true}) as any[][];for(let hi=0;hi<rows.length;hi++){const ids=rows[hi].map((v,j)=>['siret','n° siret','no siret','code postal','cp'].includes(norm(v))?j:-1).filter(j=>j>=0);if(ids.length){for(let i=hi+1;i<rows.length;i++)for(const j of ids)rows[i][j]=String(raw[i]?.[j]??'');break;}}}return rows;}
export async function importStudents(file:File){const rows=await readWorkbook(file),hi=rows.findIndex(r=>r.some(v=>['nom','eleve','name','nom complet'].includes(norm(v))));if(hi<0)throw Error('En-têtes attendus : nom, prénom, classe, email.');const h=rows[hi].map(norm),get=(r:any[],names:string[])=>r[h.findIndex(x=>names.includes(x))]||'';const students=rows.slice(hi+1).map(r=>({name:[get(r,['prenom']),get(r,['nom','nom complet','name','eleve'])].filter(Boolean).join(' '),class_name:get(r,['classe','class']),email:get(r,['email','e-mail','mail'])})).filter(s=>s.name&&s.class_name);if(!students.length)throw Error('Aucun élève valide trouvé.');const result=await api('students',{students});return result.added+' élève(s) importé(s).';}
const mapping:Row={raisonSociale:['raison sociale','entreprise','nom','raisonsociale'],denomination:['denomination commerciale','denomination','nom commercial'],siege:['siege social','siege'],activite:['activite','secteur','activity'],ape:['ape','code ape'],metiers:['metiers','metier'],secteurs:['secteurs'],adresse:['adresse','adresse 1'],codePostal:['code postal','cp','codepostal'],ville:['ville','commune'],pays:['pays'],telephone:['telephone fixe','telephone','tel'],portable:['telephone portable','portable'],email:['email','e-mail','mail'],siteWeb:['site web','siteweb','site internet'],siret:['n° siret','siret','no siret'],contactNom:['contact responsable','nom du responsable','contactnom'],contactFonction:['fonction du responsable','fonction'],contactTelephone:['telephone fixe du responsable','telephone responsable'],contactEmail:['email du responsable','e-mail responsable'],acceptation:['accepte les stagiaires','accueil des stagiaires'],capacite:['nombre max stagiaires','capacite'],lat:['latitude','lat'],lon:['longitude','lon','lng']};
export async function importCompanies(file:File,progress:(v:string)=>void){let list:Row[];if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(await file.text());list=Array.isArray(data)?data:data.companies||data.entreprises;if(!Array.isArray(list))throw Error('Le JSON doit contenir un tableau d’entreprises.');}else{const rows=await readWorkbook(file,true);let hi=rows.findIndex(r=>r.some(v=>['raison sociale','raisonsociale'].includes(norm(v))));if(hi<0)hi=rows.findIndex(r=>r.some(v=>norm(v)==='entreprise'));if(hi<0)throw Error('Colonne Raison sociale introuvable.');const h=rows[hi].map(norm);list=rows.slice(hi+1).filter(r=>r.some(Boolean)).map(r=>{const c:Row={};for(const [key,aliases] of Object.entries(mapping)){const i=h.findIndex(x=>aliases.includes(x));c[key]=i>=0?r[i]:'';}const parts=['adresse 1','adresse 2','adresse 3','adresse 4'].map(k=>r[h.indexOf(k)]).filter(Boolean);if(parts.length)c.adresse=parts.join(' ');const prenom=r[h.indexOf('prenom du responsable')];if(prenom)c.contactNom=prenom+' '+c.contactNom;if(!c.telephone)c.telephone=c.portable||'';c.metiers=String(c.metiers).split(',').map(x=>x.trim()).filter(Boolean);c.secteurs=String(c.secteurs).split(',').map(x=>x.trim()).filter(Boolean);if(!c.secteurs.length){const text=norm(c.activite+' '+c.metiers.join(' '));c.secteurs=sectors.filter(s=>text.includes(norm(s==='Industrie'?'industr':s==='Électricité'?'electric':s)));}if(!c.secteurs.length)c.secteurs=[c.activite||'À renseigner'];return c;}).filter(c=>c.raisonSociale);}let added=0,duplicates=0;for(let i=0;i<list.length;i+=100){const r=await api('companies',{companies:list.slice(i,i+100)});added+=r.added;duplicates+=r.duplicates;progress('Import : '+Math.min(i+100,list.length)+' / '+list.length);}return added+' entreprises ajoutées · '+duplicates+' doublons ignorés.';}
export async function importLegacy(file:File|undefined,studentId:string){const data=file?JSON.parse(await file.text()):{eleves:JSON.parse(localStorage.getItem('prof_eleves')||'[]'),fiches:JSON.parse(localStorage.getItem('prof_global_data')||'[]')};const oldStudents=data.eleves||[],fiches=Array.isArray(data)?data:data.fiches||[];if(oldStudents.length)await api('students',{students:oldStudents.map((s:Row)=>({name:s.nom||s.name,class_name:s.classe||s.class_name,email:s.email||''}))});let current=await api('state'),count=0;for(const f of fiches){const former=oldStudents.find((s:Row)=>s.id===f.eleveId),student=former?current.students.find((s:Row)=>s.name===(former.nom||former.name)&&s.class_name===(former.classe||former.class_name)):current.students.find((s:Row)=>s.id===studentId);if(!student)continue;let company=current.companies.find((c:Row)=>norm(c.raisonSociale)===norm(f.nom));if(!company){await api('companies',{raisonSociale:f.nom,adresse:f.adresse||'',telephone:f.tel||'',email:f.email||'',activite:f.secteur||'',secteurs:[f.secteur||'À renseigner'],lat:f.lat,lon:f.lon??f.lng});current=await api('state');company=current.companies.find((c:Row)=>norm(c.raisonSociale)===norm(f.nom));}if(!company)continue;await api('reports',{studentId:student.id,companyId:company.id,status:f.statut==='Positive'?'Accepté':f.statut==='Négative'?'Refusé':'En attente',date:/^\d{4}-\d{2}-\d{2}$/.test(f.date||'')?f.date:today(),method:f.moyen,contact:f.contactNom,notes:f.notes||'Import de la première version.'});count++;}return count+' comptes rendus importés · '+(fiches.length-count)+' sans élève associé ignorés.';}
