'use client';
import {useState,useMemo,useEffect} from 'react';
import {Users,Upload,KeyRound,ClipboardCheck,Mail,Trash2} from 'lucide-react';
import {type Row} from './helpers';
import {Status} from './components';
import StudentDeleteDialog from './student-delete-dialog';
export default function StudentDirectory({students,reports,busy,onImport,onEdit,onAccess,onFollow,onDelete}:Row){
 const [deleting,setDeleting]=useState<Row[]|null>(null);
 const [className,setClassName]=useState(''),[mode,setMode]=useState(''),[one,setOne]=useState(''),[selected,setSelected]=useState<string[]>([]),[nameQuery,setNameQuery]=useState('');
 const classes=[...new Set<string>(students.map((s:Row)=>s.class_name))].sort((a,b)=>a.localeCompare(b,'fr',{numeric:true}));
 const members=useMemo(()=>students.filter((s:Row)=>s.class_name===className).sort((a:Row,b:Row)=>a.name.localeCompare(b.name,'fr')),[students,className]);
 const visible=!className?[]:mode==='all'?members:mode==='one'?members.filter((s:Row)=>s.id===one):mode==='selection'?members.filter((s:Row)=>selected.includes(s.id)):[];
 useEffect(()=>{if(className&&!students.some((s:Row)=>s.class_name===className)){setClassName('');setMode('');setOne('');setSelected([]);}},[students,className]);
 return <><section className="panel student-filters"><div className="section-top"><h2><Users size={18}/> Choisir les élèves à afficher</h2><button className="pill" onClick={onImport}><Upload size={14}/> Importer</button></div><div className="student-controls"><label>1. Classe<select aria-label="Classe des élèves" value={className} onChange={e=>{setClassName(e.target.value);setMode('');setOne('');setSelected([]);setNameQuery('');}}><option value="">Choisir une classe…</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label><label>2. Affichage<select aria-label="Afficher les élèves" disabled={!className} value={mode} onChange={e=>{setMode(e.target.value);setOne('');setSelected([]);}}><option value="">Choisir les élèves…</option><option value="all">Tous les élèves de cette classe</option><option value="one">Un élève précis</option><option value="selection">Une sélection d’élèves</option></select></label>{mode==='one'&&<label>3. Élève<select aria-label="Choisir un élève précis" value={one} onChange={e=>setOne(e.target.value)}><option value="">Choisir un élève…</option>{members.map((s:Row)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}{mode==='selection'&&<details className="student-picker"><summary>Choisir les élèves ({selected.length})</summary><div className="picker-body"><input aria-label="Rechercher dans la classe" placeholder="Rechercher un nom…" value={nameQuery} onChange={e=>setNameQuery(e.target.value)}/><div className="picker-list">{members.filter((s:Row)=>s.name.toLocaleLowerCase('fr').includes(nameQuery.toLocaleLowerCase('fr'))).map((s:Row)=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,s.id]:old.filter(id=>id!==s.id))}/>{s.name}</label>)}</div><button className="text-button" onClick={()=>setSelected([])}>Tout désélectionner</button></div></details>}</div><p className="compact-help">Aucun élève n’apparaît avant le choix d’une classe et d’un affichage. Cliquez sur son nom pour modifier sa fiche.</p></section>
 {visible.length>0&&<section className="panel list-panel student-results"><div className="list-head"><h2>{className} <span className="result-count">{visible.length} élève{visible.length>1?'s':''}</span></h2><button className="pill danger" disabled={busy} onClick={()=>setDeleting([...visible])}><Trash2 size={14}/> Supprimer {visible.length===1?'cet élève':'les '+visible.length+' élèves affichés'}</button></div><div className="table-scroll"><table className="data-table student-table"><thead><tr><th>Élève</th><th>E-mail</th><th>Démarches</th><th>PFMP</th><th>Accès personnel</th></tr></thead><tbody>{visible.map((s:Row)=><tr key={s.id}><td><button className="name" onClick={()=>onEdit(s)}>{s.name}</button></td><td>{s.email||<span className="email-missing"><Mail size={12}/> E-mail manquant</span>}</td><td><button className="text-button" onClick={()=>onFollow(s)} aria-label={'Suivi de '+s.name}><ClipboardCheck size={13}/> {reports.filter((r:Row)=>r.student_id===s.id).length} démarche(s)</button></td><td><Status value={reports.some((r:Row)=>r.student_id===s.id&&r.status==='Accepté')?'Accepté':'En recherche'}/></td><td><div className="student-row-actions"><button className={'pill '+(s.email?'access-button':'email-button')} disabled={busy} onClick={()=>onAccess(s)}><KeyRound size={13}/>{s.email?'Gérer l’accès':'Renseigner l’e-mail'}</button><button className="pill danger" disabled={busy} aria-label={'Supprimer '+s.name} onClick={()=>setDeleting([s])}><Trash2 size={13}/> Supprimer</button></div></td></tr>)}</tbody></table></div></section>}
 {className&&mode&&visible.length===0&&<p className="compact-help">{!members.length?'Aucun élève dans cette classe.':mode==='one'?'Choisissez un élève dans le menu.':mode==='selection'?'Cochez les élèves à afficher dans « Choisir les élèves ».':''}</p>}
 {deleting&&<StudentDeleteDialog students={deleting} busy={busy} onClose={()=>setDeleting(null)} onDelete={onDelete}/>}
 </>;
}
